steps:
  # Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/amenguide-backend:${SHORT_SHA}', '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/amenguide-backend:latest', './backend']
  
  # Build Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/amenguide-git:${SHORT_SHA}'
      - '-t'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/amenguide-git:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://amenguide-backend-775250805671.us-west1.run.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_KAKAO_MAP_API_KEY=YOUR_KEY_HERE'
      - './frontend'


images:
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/amenguide-backend'
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/amenguide-git'
